name: test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: simple-coverage-diff
        uses: mtgto/simple-coverage-diff-action@update-comment
        with:
          github-token: ${{ github.token }}
          base-summary-json: coverage-summary-base.json
          head-summary-json: coverage-summary-head.json
          body-header: |
            これはヘッダーです
          body-footer: |
            これはフッターです
          update-if-exists: replace
