name: test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: simple-coverage-diff
        uses: mtgto/simple-coverage-diff-action@update-comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-summary-json: coverage/coverage-summary.json
          head-summary-json: coverage/coverage-summary.json
          body-header: |
            これはヘッダーです
          body-footer: |
            これはフッターです
